MealManagementSystem/MealManagementSystem/Areas/Admin/Models/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MealManagementSystem.Areas.Admin.Models
{
    public class DetailsViewModel
    {
        [Key]
        public int DetailsId { get; set; }
        public string Name { get; set; }

        [Display(Name="Total Meal")]
        public double NumberOfMeal { get; set; }

        [Display(Name = "Meal Spent")]
        public double MealSpent { get; set; }

        [Display(Name = "Extra Spent")]
        public double ExtraSpent { get; set; }

        [Display(Name = "Total Spent")]
        public double TotalSpent { get; set; }
        public double Paid { get; set; }
        public double Payable { get; set; }
        public double Receivable { get; set; }

        [Display(Name = "Meal Rate")]
        public double MealRate { get; set; }

    }
}

MealManagementSystem/MealManagementSystem/Areas/Admin/Models/Meal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MealManagementSystem.Models
{
   [ MetadataType(typeof(MealMetaData))]
    public partial class Meal
    {
    }

    public class MealMetaData
    {
        [Required]
        [Display(Name ="Member Name")]
        public int MemberId { get; set; }
    }
}

MealManagementSystem/MealManagementSystem/Models/Meal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int MealId { get; set; }
        public int MemberId { get; set; }
        public System.DateTime Date { get; set; }
        public double Breakfast { get; set; }
        public double Lunch { get; set; }
        public double Dinner { get; set; }
        public double Total { get; set; }
    
        public virtual User User { get; set; }
    }
}

MealManagementSystem/MealManagementSystem/Areas/Admin/Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MealManagementSystem.Models;

namespace MealManagementSystem.Areas.Admin.Controllers
{
    public class MealsController : Controller
    {
        private MealDBContex db = new MealDBContex();

        //View Meal By Date
        public ActionResult ViewMeal()
        {

            return View();
        }
        [HttpPost]
        public ActionResult ViewMeal(DateTime Date)
        {
            
            return View(db.Meals.Where(model=>model.Date==Date).ToList());
        }

        // GET: Admin/Meals
        public ActionResult Index()
        {
            var meals = db.Meals.Include(m => m.User);
            return View(meals.ToList());
        }

        // GET: Admin/Meals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // GET: Admin/Meals/Create
        public ActionResult Create()
        {


            ViewBag.MemberId = new SelectList(db.Users.Where(model=>model.UserType=="Member"), "UserId", "UserName");
            return View();
        }

        // POST: Admin/Meals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MealId,MemberId,Date,Breakfast,Lunch,Dinner")] Meal meal)
        {
            meal.Total = meal.Breakfast + meal.Lunch + meal.Dinner;
            if (db.Meals.Any(model => model.Date == meal.Date && model.MemberId==meal.MemberId))
            {
                ModelState.AddModelError("Date", "Meal is already given for this Date ");
            }
            if (ModelState.IsValid)
            {
                db.Meals.Add(meal);
                db.SaveChanges();
                ViewBag.SuccessMsg = "Meal Saved Successfully....";
                ModelState.Clear();
                ViewBag.MemberId = new SelectList(db.Users.Where(model => model.UserType == "Member"), "UserId", "UserName");
                return View();
            }

            ViewBag.MemberId = new SelectList(db.Users.Where(model=>model.UserType=="Member"), "UserId", "UserName", meal.MemberId);
            return View(meal);
        }



        // GET: Admin/Meals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            ViewBag.MemberId = new SelectList(db.Users, "UserId", "UserName", meal.MemberId);
            return View(meal);
        }

        // POST: Admin/Meals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MealId,MemberId,Date,Breakfast,Lunch,Dinner,Total")] Meal meal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(meal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MemberId = new SelectList(db.Users, "UserId", "UserName", meal.MemberId);
            return View(meal);
        }

        // GET: Admin/Meals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // POST: Admin/Meals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Meal meal = db.Meals.Find(id);
            db.Meals.Remove(meal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MealManagementSystem/MealManagementSystem/Areas/Admin/Views/Meals/Create.cshtml
@model MealManagementSystem.Models.Meal

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="h2 text-center">Make a Meal</div>
    </div>
    <div class="panel-body">
       <div class="h3 text-center">@DateTime.Now.ToString("MMMM") @DateTime.Now.Day , @DateTime.Now.Year</div>
        <br />
            @if (ViewBag.SuccessMsg != null)
            {
                <div class="text-center h5" style="color:green;font-weight:bold">@ViewBag.SuccessMsg</div>
            }
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="col-md-6">
                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.MemberId, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownListFor(model=>model.MemberId, null,"---Select Option---", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">


                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-md-6">
                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Breakfast, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model=>model.Breakfast,new List<SelectListItem>()
                       {
                           new SelectListItem(){ Text="0",Value="0" },
                           new SelectListItem(){ Text="0.5",Value="0.5" },
                           new SelectListItem(){ Text="1",Value="1" },
                           new SelectListItem(){ Text="2",Value="2" },
                           new SelectListItem(){ Text="3",Value="3" },
                           new SelectListItem(){ Text="4",Value="4" },
                           new SelectListItem(){ Text="5",Value="5" },
                           new SelectListItem(){ Text="6",Value="6" },
                           new SelectListItem(){ Text="7",Value="7" },
                           new SelectListItem(){ Text="8",Value="8" },
                           new SelectListItem(){ Text="9",Value="9" },
                           new SelectListItem(){ Text="10",Value="10" }
                       },"---Select Option---",new {@class="form-control" })
                            @Html.ValidationMessageFor(model => model.Breakfast, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Lunch, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Lunch, new List<SelectListItem>()
                       {
                           new SelectListItem(){ Text="0",Value="0" },
                           new SelectListItem(){ Text="0.5",Value="0.5" },
                           new SelectListItem(){ Text="1",Value="1" },
                           new SelectListItem(){ Text="2",Value="2" },
                           new SelectListItem(){ Text="3",Value="3" },
                           new SelectListItem(){ Text="4",Value="4" },
                           new SelectListItem(){ Text="5",Value="5" },
                           new SelectListItem(){ Text="6",Value="6" },
                           new SelectListItem(){ Text="7",Value="7" },
                           new SelectListItem(){ Text="8",Value="8" },
                           new SelectListItem(){ Text="9",Value="9" },
                           new SelectListItem(){ Text="10",Value="10" }
                       }, "---Select Option---", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Lunch, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Dinner, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Dinner, new List<SelectListItem>()
                       {
                           new SelectListItem(){ Text="0",Value="0" },
                           new SelectListItem(){ Text="0.5",Value="0.5" },
                           new SelectListItem(){ Text="1",Value="1" },
                           new SelectListItem(){ Text="2",Value="2" },
                           new SelectListItem(){ Text="3",Value="3" },
                           new SelectListItem(){ Text="4",Value="4" },
                           new SelectListItem(){ Text="5",Value="5" },
                           new SelectListItem(){ Text="6",Value="6" },
                           new SelectListItem(){ Text="7",Value="7" },
                           new SelectListItem(){ Text="8",Value="8" },
                           new SelectListItem(){ Text="9",Value="9" },
                           new SelectListItem(){ Text="10",Value="10" }
                       }, "---Select Option---", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Dinner, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-10">
                    <input type="submit" value="Save" class="btn btn-block btn-success"  />
                </div>
            </div>

        }

    </div>
</div>



<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#Date").datepicker({
                
            });
            
            //$("#Breakfast").blur(function () {
            //    debugger
            //    var breakfastValue = $(this).val();
            //    var lunchValue = $("#Lunch").val();
            //    var dinnerValue = $("#Dinner").val();
            //    var Total = parseFloat(breakfastValue) + lunchValue + dinnerValue;
            //    $("#Total").val(Total);
            //})
        })
    </script>
}

MealManagementSystem/MealManagementSystem/Areas/Admin/Views/Meals/Delete.cshtml
@model MealManagementSystem.Models.Meal

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Meal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Breakfast)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Breakfast)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lunch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lunch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dinner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dinner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MealManagementSystem/MealManagementSystem/Areas/Admin/Views/Meals/Details.cshtml
@model MealManagementSystem.Models.Meal

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Meal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Breakfast)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Breakfast)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lunch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lunch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dinner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dinner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MealId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MealManagementSystem/MealManagementSystem/Areas/Admin/Views/Meals/Edit.cshtml
@model MealManagementSystem.Models.Meal

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Meal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MealId)

        <div class="form-group">
            @Html.LabelFor(model => model.MemberId, "MemberId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Breakfast, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Breakfast, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Breakfast, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lunch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lunch, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lunch, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dinner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dinner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dinner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MealManagementSystem/MealManagementSystem/Areas/Admin/Views/Meals/Index.cshtml
@model IEnumerable<MealManagementSystem.Models.Meal>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Breakfast)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lunch)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dinner)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Breakfast)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lunch)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dinner)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MealId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MealId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MealId })
        </td>
    </tr>
}

</table>

MealManagementSystem/MealManagementSystem/Areas/Admin/Views/Meals/ViewMeal.cshtml
@model IEnumerable<MealManagementSystem.Models.Meal>

@{
    ViewBag.Title = "ViewMeal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">

    </div>
    <div class="panel-body">
        @using (Html.BeginForm("ViewMeal","Meals",FormMethod.Post))
        {
            <div class="col-md-4 col-md-offset-4 ">
                <div class="form-group">
                    <div class="col-md-8">
                        <input type="date" id="Date" name="Date" required class="form-control" />
                    </div>
                    <div class="col-md-4">
                        <input type="submit" id="btnSubmit" name="btnSubmit" value="Search By Date" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
        
        <br />
        <br />
        <br />
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.User.FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Breakfast)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Lunch)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dinner)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
                <th></th>
            </tr>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Breakfast)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Lunch)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Dinner)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Total)
                        </td>

                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.MealId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.MealId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.MealId })
                        </td>
                    </tr>
                }
            }


        </table>
    </div>
    <div class="panel-footer">

    </div>
</div>


<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}